name: cocoapods-publish

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: CocoaPod to Publish
        options: 
        - OpenPass
        - OpenPassObjC
      version:
        description: 'Tag name for release (e.g. "1.0.0")'
        required: true
        type: string

run-name: "Publish CocoaPod ${{ inputs.name }} version ${{ inputs.version }}"

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:
  publish:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Set up
      run: mkdir tmp

    - name: Update podspec
      run: |
        jq --arg VERSION "${{ inputs.version }}" '. | .version |= $VERSION | .source.tag |= $VERSION' ${{ github.event.inputs.name }}.podspec.json > tmp/${{ github.event.inputs.name }}.podspec.json
        
    - name: Lint podspec
      run: |
        pod spec lint tmp/${{ github.event.inputs.name }}.podspec.json

    - name: Push podspec to Cocoapods trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push tmp/${{ github.event.inputs.name }}.podspec.json

    - name: Clean up
      run: rm -r tmp
