name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:

  test-code-changes:
    name: Test Code Changes
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install swiftlint

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Run unit tests on iOS
        run: xcodebuild test -scheme OpenPass -destination "OS=18.1,name=iPhone 15"

      - name: Run ObjC unit tests on iOS
        run: xcodebuild test -scheme OpenPassObjC -destination "OS=18.1,name=iPhone 15"

      - name: Run unit tests on tvOS
        run: xcodebuild test -scheme OpenPass -destination "OS=18.1,name=Apple TV"

      - name: Run ObjC unit tests on tvOS
        run: xcodebuild test -scheme OpenPassObjC -destination "OS=18.1,name=Apple TV"

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --strict --reporter github-actions-logging

      - name: Lint OpenPass podspec
        run: pod lib lint OpenPass.podspec.json --verbose

  device-tests:
    uses: ./.github/workflows/device-tests.yml
    with: 
      ref: ${{ github.head_ref }}
    secrets:
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      FASTLANE_MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      MAIL_SLURP_API_KEY: ${{ secrets.MAIL_SLURP_API_KEY }}
      READ_ONLY_CONTENT_APP_PRIVATE_KEY: ${{ secrets.READ_ONLY_CONTENT_APP_PRIVATE_KEY }}
